language: cpp
matrix:
  include:
    - os: osx

before_install:
  - brew update
  - brew outdated boost || brew upgrade boost

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
