language: cpp
matrix:
  include:
    - os: osx
      osx_image: xcode11.2

before_install:
  - brew update
  - brew outdated catch2 || brew upgrade catch2
  - brew outdated boost || brew upgrade boost

script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - make test
